openapi: '3.0.0'
info:
  title: sample.com
  description: Swagger API 문서
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local

tags: []

paths:
  /settings:
    $ref: "./settings/settings.yaml"
  /users:
    $ref: "./users/users.yaml"

security:
  - X-Hiworks-Jwt: []
  - Authorization-Type: []

components:
  schemas:
    $ref: "./components/schemas.yaml"
  responses:
    $ref: "./components/responses.yaml"