get:
  tags:
    - 'Setting'
  summary: '설정 조회'
  responses:
    '200':
      description: 'Success'
      content:
        application/json:
          schema:
            $ref: '#/schemas/Setting'
          examples:
            settingExample:
              $ref: '#/examples/Setting'
    '400':
      $ref: '../components/responses.yaml#/BadRequest'
patch:
  tags:
    - 'Setting'
  summary: '설정 수정'
  requestBody:
    description: '설정 업데이트 요청'
    content:
      application/json:
        schema:
          $ref: '#/schemas/SettingUpdate'
        examples:
          settingUpdateExample:
            $ref: '#/examples/SettingUpdate'
      application/x-www-form-urlencoded:
        schema:
          $ref: '#/schemas/SettingUpdate'
        examples:
          settingUpdateExample:
            $ref: '#/examples/SettingUpdate'
  responses:
    '200':
      description: 'Success'
      content:
        application/json:
          schema:
            $ref: '#/schemas/Setting'
          examples:
            settingExample:
              $ref: '#/examples/Setting'
    '400':
      $ref: '../components/responses.yaml#/BadRequest'



schemas:
  Setting:
    type: object
    properties:
      company_id:
        type: integer
        description: '회사 식별자'
      name:
        type: string
        description: '회사명'
      is_something_used:
        type: boolean
        description: '기능 사용 여부'
      created_by:
        type: integer
        description: '생성자 식별자'
      updated_by:
        type: integer
        description: '수정자 식별자'
      created_at:
        type: string
        format: date-time
        description: '생성일'
      updated_at:
        type: string
        format: date-time
        description: '수정일'
  SettingUpdate:
    type: object
    properties:
      name:
        type: string
        description: '회사명'
      is_something_used:
        type: boolean
        description: '기능 사용 여부'

examples:
  Setting:
    value:
      data:
        company_id: 1
        name: 'sample'
        is_something_used: true
        created_by: 1
        updated_by: 1
        created_at: '2023-05-08T01:59:57.000Z'
        updated_at: '2023-05-08T01:59:57.000Z'
      meta: {}

  SettingUpdate:
    value:
      name: 'sample update'
      is_something_used: false

